# Generated by Django 3.1.7 on 2021-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listall', '0004_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
